name: Win64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
      - name: Install Dependencies
        run: |
            choco install rakudostar
            choco install wget
            choco install dejavufonts
            zef --exclude="z" install --debug --/test --test-depends --deps-only .
      - name: Run Tests
        run: zef install --debug .
